<a href="https://colab.research.google.com/github/itripathi423-a11y/Concept-of-AI/blob/master/Workshop_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np
arr1=np.array((2,2))
print(arr1)

[2 2]


#2. Initialize an all one array with size 4X2.

In [ ]:
import numpy as np
arr2=np.ones((4,2))
print(arr2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


#3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
import numpy as np
arr3=np.full((2,2),5)
print(arr3)

[[5 5]
 [5 5]]


#4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
import numpy as np
arr4=np.array([[1,2],[3,4]])
arr_zero=np.zeros_like(arr4)
print(arr_zero)

[[0 0]
 [0 0]]


#5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
import numpy as np
arr5=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_one=np.fives_like(arr5)
print(arr_one)

AttributeError: module 'numpy' has no attribute 'fives_like'

#6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np
new_list=[1,2,3,4,5,6,7,8,9,0]
arr6=np.fives_like(new_list)
print(arr6)

AttributeError: module 'numpy' has no attribute 'fives'

#Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
import numpy as np
arr7=np.arange(10,49)
print(arr7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
import numpy as np
arr8=np.arange(0,9)
reshape_array=np.reshape(arr8,(3,3))
print(reshape_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
import numpy as np
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
import numpy as np
arr1=np.random.random(30)
mean=arr1.mean()
print(arr1)
print(mean)

[0.28824752 0.61160034 0.48018893 0.19635991 0.26392866 0.23206032
 0.26831846 0.73068567 0.93288805 0.428527   0.31016604 0.47873137
 0.34052994 0.37907173 0.81799756 0.5899388  0.68739073 0.33542023
 0.99170226 0.0195495  0.28880711 0.87461141 0.57376892 0.69328523
 0.54343847 0.59687919 0.2408056  0.97938111 0.47822029 0.38233093]
0.501161042032173


#5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np
arr1=np.random.random((10,10))
mini=np.min(arr1)
maxi=np.max(arr1)
print(arr1)
print(mini)
print(maxi)

[[0.9341189  0.24631746 0.58294676 0.86170302 0.41363944 0.67899399
  0.24913947 0.09064505 0.51811912 0.04668815]
 [0.08922307 0.59012881 0.74698334 0.20478515 0.01219958 0.11893116
  0.20483756 0.34954181 0.34906316 0.08093978]
 [0.5261666  0.11355922 0.33351475 0.10358051 0.57611239 0.04003236
  0.73462291 0.5344895  0.03549012 0.63969986]
 [0.6323738  0.66759861 0.55553215 0.74644937 0.18956364 0.10029866
  0.6698925  0.73858231 0.37670898 0.57264536]
 [0.01357719 0.0957251  0.64604185 0.77888218 0.08359135 0.36690619
  0.92064659 0.16731656 0.52902387 0.09111062]
 [0.99797213 0.80540805 0.59006737 0.56694253 0.8756837  0.50625243
  0.05086929 0.59001962 0.26046235 0.70859888]
 [0.60081428 0.90027062 0.04414612 0.9754888  0.63799014 0.37234693
  0.47257035 0.80101936 0.1160468  0.02365278]
 [0.86784162 0.48500075 0.30419313 0.61269436 0.59125902 0.29459034
  0.74109796 0.15170918 0.93177423 0.76947578]
 [0.3892362  0.35460859 0.56392141 0.92091586 0.78478995 0.27812645
  0.10720927

#6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
import numpy as np
arr1=np.zeros((4,6))
arr1[:, 4] = 1
print(arr1)

[[0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]]


#7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
import numpy as np
arr = np.array([1, 2, 0, 0, 4, 0])
print(arr[::-1])

[0 4 0 0 2 1]


#8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
import numpy as np
arr=np.ones((4,4))
arr[1:-1,1:-1]=0
print (arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np
arr=np.ones((8,8))
arr[1::2, ::2]=0
arr[::2, 1::2]=0
print (arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
addition1=np.add(x,y)
addition2=np.add(v,w)
print("Addition of x and y=",addition1)
print("Addition of v and w=",addition1)

Addition of x and y= [[ 6  8]
 [10 13]]
Addition of v and w= [[ 6  8]
 [10 13]]


#2. Subtract the two array.

In [ ]:
import numpy as np
x = np.array([[1,3],[4,5]])
y = np.array([[5,6],[6,8]])
v = np.array([9,10])
w = np.array([11,12])
subtract1=np.subtract(x,y)
subtract2=np.subtract(v,w)
print("Subtract of x and y=",subtract1)
print("Subtract of v and w=",subtract2)

Subtract of x and y= [[-4 -3]
 [-2 -3]]
Subtract of v and w= [-2 -2]


#3. Multiply the array with any integers of your choice.

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
v = np.array([9,10])
multiply1=np.multiply(x,2)
multiply2=np.multiply(v,3)
print("Multiplying x with 2=",multiply1)
print("Multiplying v with 3=", multiply2)

Multiplying x with 2= [[ 2  4]
 [ 6 10]]
Multiplying v with 3= [27 30]


#4. Find the square of each element of the array.

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
square1=np.square(x)
square2=np.square(y)
square3=np.square(v)
square4=np.square(w)
print("Square of x=",square1)
print("Square of y=",square2)
print("Square of v=",square3)
print("Square of w=",square4)

Square of x= [[ 1  4]
 [ 9 25]]
Square of y= [[25 36]
 [49 64]]
Square of v= [ 81 100]
Square of w= [121 144]


#5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
Product1=np.dot(v,w)
Product2=np.dot(x,v)
Product3=np.dot(x,y)
print("Dot product of v and w=",Product1)
print("Dot product of x and v=",Product2)
print("Dot product of x and y=",Product3)

Dot product of v and w= 219
Dot product of x and v= [29 77]
Dot product of x and y= [[19 22]
 [50 58]]


#6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
hstacked=np.hstack((x,y))
vstacked=np.vstack((v,w))
print("Concatenate along row=",hstacked)
print("Concatenate along row=",vstacked)

Concatenate along row= [[1 2 5 6]
 [3 5 7 8]]
Concatenate along row= [[ 9 10]
 [11 12]]


#7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
v = np.array([9,10])
concate_xaxis=np.concatenate((x,v),axis=0)
print(concate_xaxis)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

#Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)T = BTAT

In [ ]:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

Inverse_of_A=np.linalg.inv(A)
Identity=np.dot(A,Inverse_of_A)
print(Identity)
print("\n")
AB=np.dot(A,B)
BA=np.dot(B,A)
print("A * B =", AB)
print("B * A =", BA)
print("\n")
transpose_AB=np.transpose(AB)
transpose_A=np.transpose(A)
transpose_B=np.transpose(B)
A_transpose_B_transpose=np.dot(transpose_B,transpose_A)
print("Transpose of AB=",transpose_AB)
print("Transpose of A and B=",A_transpose_B_transpose)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


A * B = [[23 13]
 [51 29]]
B * A = [[36 44]
 [13 16]]


Transpose of AB= [[23 51]
 [13 29]]
Transpose of A and B= [[23 51]
 [13 29]]


#• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
import numpy as np
A=np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B=np.array([-1,-3,9])
A_Inverse=np.linalg.inv(A)
X=np.dot(A_Inverse,B)
print(X)
print("\n")
X2=np.linalg.solve(A,B)
print(X2)

[ 2.  1. -2.]


[ 2.  1. -2.]
